In [1]:
import pandas as pd

In [2]:
series1 = pd.Series([1,2,3,4,5])
print(series1)
print(type(series1))

# index
print(series1[0])
print(series1[3])

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>
1
4

In [3]:
series2 = pd.Series([23, 24, 25, 26], index=["Adam", "Eve", "Bob", "Charlie"])
print(series2)
print(series2["Bob"])

Adam       23
Eve        24
Bob        25
Charlie    26
dtype: int64
25

In [4]:
s1 = pd.Series([1,2,3,4,5])
s2 = pd.Series([10,9,8,7,6])

s1+s2

s1[0] = 100
changed_s1 = s1.drop(0)

print(s1)
print(changed_s1)

0    100
1      2
2      3
3      4
4      5
dtype: int64
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
# Dataframe

info = {
    "Name": ["Ansh", "Nandani", "Shivam"],
    "Age": [20,19,21],
    "CGPA": [7.5, 9.5, 8.5],
}

df = pd.DataFrame(info)
print(type(df))
print(df.index)
print(df.columns)

<class 'pandas.DataFrame'>
RangeIndex(start=0, stop=3, step=1)
Index(['Name', 'Age', 'CGPA'], dtype='str')

In [6]:
df

      Name  Age  CGPA
0     Ansh   20   7.5
1  Nandani   19   9.5
2   Shivam   21   8.5

In [7]:
df2 = pd.DataFrame([["Ansh", 20], ["Nandani", 19], ["Shivam", 21]], columns=["Name", "Age"])

In [8]:
df2

      Name  Age
0     Ansh   20
1  Nandani   19
2   Shivam   21

In [9]:
import numpy as np

np_arr = np.array([[1,2,3], [4,5,6]])

df3 = pd.DataFrame(np_arr, columns=["A","B","C"])

In [10]:
df3

   A  B  C
0  1  2  3
1  4  5  6

In [11]:
# CSV  data

df4 = pd.read_csv("employee_data.csv")
print(df4, type(df4))

   ID     Name  Age Department  Salary
0   1    Alice   25         HR   55000
1   2      Bob   32         IT   72000
2   3  Charlie   28    Finance   48000
3   4    David   45  Marketing   91000
4   5      Eva   38         IT   65000
5   6    Frank   29    Finance   50000
6   7    Grace   41         HR   82000
7   8   Hannah   26  Marketing   47000
8   9      Ian   35         IT   75000
9  10    Julia   30    Finance   60000 <class 'pandas.DataFrame'>

In [12]:
df4.head() # Rows from top
df4.tail() # Rows From bottom
df4.sample(5) # Random Rows

df4.info() # Gives info of the dataframe
df4.shape
df4.describe()
df4.columns
df4.nunique()

<class 'pandas.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          10 non-null     int64
 1   Name        10 non-null     str
 2   Age         10 non-null     int64
 3   Department  10 non-null     str
 4   Salary      10 non-null     int64
dtypes: int64(3), str(2)
memory usage: 628.0 bytes

ID            10
Name          10
Age           10
Department     4
Salary        10
dtype: int64

In [13]:
# Raw Data

df = pd.read_csv("raw_data.csv")

In [14]:
df.drop_duplicates(inplace=True)

df = df.fillna(0)

In [15]:
# Feature Engineering
df2 = df.copy()

df2["tax"] = df2["income"].apply(lambda x: "20%" if x >= 50000 else "10%")
gender_map = {"Male": "M", "Female": "F", "Unknown": "U"}
df2["gender"] = df2["gender"].map(gender_map)

df2 = df2.assign(new_income = df2["income"] * 1.1)

df2["country"] = df2["country"].replace("USA", "US")

df2.columns = [column.capitalize() for column in df2.columns]
df2 = df2.rename(columns={"Income":"Salary"})
df2 = df2.rename(index={1:"First"})

# df2["Salary"].sort_values()
df2 = df2.sort_values(["Salary", "Age"], ascending=False)
df2 = df2.reset_index(drop=True)

In [16]:
df2

   Id          Name   Age Country Gender   Salary  Tax  New_income
0   6             0  45.0   India      F  73000.0  20%     80300.0
1   7    Ahmed Khan  38.0       0      M  68000.0  20%     74800.0
2   8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
3   2    Jane Smith   0.0  Canada      F  62000.0  20%     68200.0
4  10   Emily Davis  31.0      US    NaN  58000.0  20%     63800.0
5   1      John Doe  29.0      US      M  55000.0  20%     60500.0
6   5        Li Wei  27.0   China      M  51000.0  20%     56100.0
7   3          Alex   0.0      US      U  47000.0  10%     51700.0
8   9   Carlos Ruiz   0.0  Mexico      M  45000.0  10%     49500.0
9   4  Maria Garcia  34.0   Spain      F      0.0  10%         0.0

In [17]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   0.0  Canada   Female  62000.0
3    3          Alex   0.0     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      0.0
5    5        Li Wei  27.0   China     Male  51000.0
6    6             0  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0       0     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   0.0  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA        0  58000.0

In [18]:
# Practice Task
# Shift id column to end

ans = df.copy()
ans[[col for col in ans.columns if col != "id"] + ["id"]]

            name   age country   gender   income  id
0       John Doe  29.0     USA     Male  55000.0   1
2     Jane Smith   0.0  Canada   Female  62000.0   2
3           Alex   0.0     USA  Unknown  47000.0   3
4   Maria Garcia  34.0   Spain   Female      0.0   4
5         Li Wei  27.0   China     Male  51000.0   5
6              0  45.0   India   Female  73000.0   6
7     Ahmed Khan  38.0       0     Male  68000.0   7
8     Rachel Lee  29.0     USA   Female  62000.0   8
9    Carlos Ruiz   0.0  Mexico     Male  45000.0   9
10   Emily Davis  31.0     USA        0  58000.0  10

In [19]:
df2

   Id          Name   Age Country Gender   Salary  Tax  New_income
0   6             0  45.0   India      F  73000.0  20%     80300.0
1   7    Ahmed Khan  38.0       0      M  68000.0  20%     74800.0
2   8    Rachel Lee  29.0      US      F  62000.0  20%     68200.0
3   2    Jane Smith   0.0  Canada      F  62000.0  20%     68200.0
4  10   Emily Davis  31.0      US    NaN  58000.0  20%     63800.0
5   1      John Doe  29.0      US      M  55000.0  20%     60500.0
6   5        Li Wei  27.0   China      M  51000.0  20%     56100.0
7   3          Alex   0.0      US      U  47000.0  10%     51700.0
8   9   Carlos Ruiz   0.0  Mexico      M  45000.0  10%     49500.0
9   4  Maria Garcia  34.0   Spain      F      0.0  10%         0.0

In [20]:
df2.to_csv("sorted_data.csv")

In [49]:
# Grouping and Aggregation
df2.groupby("Country")["Salary"].mean()
df2.groupby("Country")["Salary"].sum()
df2.groupby("Gender")["Salary"].max()
df2.groupby("Gender")["Salary"].count()

df2.groupby("Country")["Salary"].agg(["mean", "sum", "max","min", "count"])

df2.groupby("Gender")["Salary"].agg(avg_salary = "mean",sum_salary = "sum",max_salary = "max",min_salary = "min",count = "count")

df2.groupby("Country").agg({
    "Salary" : "mean",
    "Age": "max"
})
df2.groupby("Country").agg(
    avg_salary = ("Salary", "mean"),
    max_age = ("Age", "max")
)

         avg_salary  max_age
Country
0           68000.0     38.0
Canada      62000.0      0.0
China       51000.0     27.0
India       73000.0     45.0
Mexico      45000.0      0.0
Spain           0.0     34.0
US          55500.0     31.0